=== FrogletApps/RoboRef/public/rules/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://roboref.pages.dev/rules/schema.json",
  "title": "Referee FYI Game Schema",
  "description": "Describes the shape of Referee FYI game descriptions.",
  "type": "object",
  "required": ["title", "season", "programs", "ruleGroups"],
  "properties": {
    "title": {
      "type": "string",
      "description": "The game name."
    },
    "season": {
      "type": "string",
      "description": "The year (ex. 2024-2025) that the game applies to."
    },
    "qa": {
      "type": "string",
      "format": "uri",
      "description": "The URL to the Q&A site for the season."
    },
    "programs": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/program"
      },
      "description": "The programs that the game is for."
    },
    "ruleGroups": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/ruleGroup"
      },
      "description": "The rule groups in the game."
    }
  },
  "$defs": {
    "program": {
      "enum": ["V5RC", "VURC", "VAIRC", "VIQRC", "ADC"],
      "description": "The program abbreviation."
    },
    "ruleGroup": {
      "required": ["name", "programs", "rules"],
      "properties": {
        "name": {
          "type": "string",
          "description": "The rule group name."
        },
        "programs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/program"
          },
          "description": "The programs that the rule group is for."
        },
        "rules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/rule"
          },
          "description": "The rules in the group."
        }
      }
    },
    "rule": {
      "required": ["rule", "description", "link"],
      "properties": {
        "rule": {
          "type": "string",
          "description": "The rule code, like <SG4>`"
        },
        "description": {
          "type": "string",
          "description": "Single-sentence quick-description of rule."
        },
        "link": {
          "type": "string",
          "format": "uri",
          "description": "Game manual link to the rule."
        },
        "icon": {
          "type": "string",
          "format": "uri-reference",
          "description": "A link to a small image icon which represents the rule"
        }
      }
    }
  }
}

=== FrogletApps/RoboRef/public/rules/V5RC/2026-2027.json
{
  "$schema": "https://roboref.pages.dev/rules/schema.json",
  "title": "Override",
  "season": "2026-2027",
  "programs": [
    "V5RC",
    "VURC",
    "VAIRC"
  ],
  "ruleGroups": [
    {
      "name": "Specific Game Rules",
      "programs": [
        "V5RC",
        "VURC",
        "VAIRC"
      ],
      "rules": [
        {
          "rule": "<SG1>",
          "description": "Starting a Match",
          "link": "https://www.vexrobotics.com/override-manual#sg1"
        },
        {
          "rule": "<SG2>",
          "description": "Horizontal expansion is limited",
          "link": "https://www.vexrobotics.com/override-manual#sg2"
        },
        {
          "rule": "<SG3>",
          "description": "Vertical expansion is limited",
          "link": "https://www.vexrobotics.com/override-manual#sg3"
        },
        {
          "rule": "<SG4>",
          "description": "Keep Scoring Objects in the Field",
          "link": "https://www.vexrobotics.com/override-manual#sg4"
        },
        {
          "rule": "<SG5>",
          "description": "Each Robot gets one Pin as a Preload",
          "link": "https://www.vexrobotics.com/override-manual#sg5"
        },
        {
          "rule": "<SG6>",
          "description": "Possession is limited to a maximum of one Pin and one Cup",
          "link": "https://www.vexrobotics.com/override-manual#sg6"
        },
        {
          "rule": "<SG7>",
          "description": "Don't cross the Autonomous Line, and don't interfere with your opponents' actions",
          "link": "https://www.vexrobotics.com/override-manual#sg7"
        },
        {
          "rule": "<SG8>",
          "description": "Engage with the Midfield and Autonomous Line during the Autonomous Period at your own risk",
          "link": "https://www.vexrobotics.com/override-manual#sg8"
        },
        {
          "rule": "<SG9>",
          "description": "Alliance Goals are protected",
          "link": "https://www.vexrobotics.com/override-manual#sg9"
        },
        {
          "rule": "<SG10>",
          "description": "Scoring Objects can't be removed from neutral or opponent-Alliance Goals",
          "link": "https://www.vexrobotics.com/override-manual#sg10"
        },
        {
          "rule": "<SG11>",
          "description": "Match Loads may be introduced during the Match under certain conditions",
          "link": "https://www.vexrobotics.com/override-manual#sg11"
        },
        {
          "rule": "<SG12>",
          "description": "Some rules change during the Endgame period",
          "link": "https://www.vexrobotics.com/override-manual#sg12"
        }
      ]
    },
    {
      "name": "Scoring Rules",
      "programs": [
        "V5RC",
        "VURC",
        "VAIRC"
      ],
      "rules": [
        {
          "rule": "<SC1>",
          "description": "All scoring statuses are evaluated after the Match ends",
          "link": "https://www.vexrobotics.com/override-manual#sc1"
        },
        {
          "rule": "<SC2>",
          "description": "Placed Scoring Object criteria",
          "link": "https://www.vexrobotics.com/override-manual#sc2"
        },
        {
          "rule": "<SC3>",
          "description": "Each Placed Pin can have zero, one, or two Scored halves",
          "link": "https://www.vexrobotics.com/override-manual#sc3"
        },
        {
          "rule": "<SC4>",
          "description": "A Toggle is considered set to a color when it meets all of the following criteria",
          "link": "https://www.vexrobotics.com/override-manual#sc4"
        },
        {
          "rule": "<SC5>",
          "description": "Yellow Pin Ownership",
          "link": "https://www.vexrobotics.com/override-manual#sc5"
        },
        {
          "rule": "<SC6>",
          "description": "Robot Midfield criteria",
          "link": "https://www.vexrobotics.com/override-manual#sc6"
        },
        {
          "rule": "<SC7>",
          "description": "Autonomous Bonus criteria",
          "link": "https://www.vexrobotics.com/override-manual#sc7"
        },
        {
          "rule": "<SC8>",
          "description": "Autonomous Win Point criteria",
          "link": "https://www.vexrobotics.com/override-manual#sc8"
        }
      ]
    },
    {
      "name": "General Game Rules",
      "programs": [
        "V5RC",
        "VURC",
        "VAIRC"
      ],
      "rules": [
        {
          "rule": "<GG1>",
          "description": "Only Drive Team Members, and only in the Alliance Station",
          "link": "https://www.vexrobotics.com/override-manual#gg1"
        },
        {
          "rule": "<GG2>",
          "description": "A Team's Robot should attend every Match",
          "link": "https://www.vexrobotics.com/override-manual#gg2"
        },
        {
          "rule": "<GG3>",
          "description": "Robots on the Field must be ready to play",
          "link": "https://www.vexrobotics.com/override-manual#gg3"
        },
        {
          "rule": "<GG4>",
          "description": "Hands out of the Field",
          "link": "https://www.vexrobotics.com/override-manual#gg4"
        },
        {
          "rule": "<GG5>",
          "description": "Match replays are allowed, but rare",
          "link": "https://www.vexrobotics.com/override-manual#gg5"
        },
        {
          "rule": "<GG6>",
          "description": "Disqualifications",
          "link": "https://www.vexrobotics.com/override-manual#gg6"
        },
        {
          "rule": "<GG7>",
          "description": "Time-outs",
          "link": "https://www.vexrobotics.com/override-manual#gg7"
        },
        {
          "rule": "<GG8>",
          "description": "Keep your Robots together",
          "link": "https://www.vexrobotics.com/override-manual#gg8"
        },
        {
          "rule": "<GG9>",
          "description": "Don't hook your Robot to the Field, and don't get Entangled",
          "link": "https://www.vexrobotics.com/override-manual#gg9"
        },
        {
          "rule": "<GG10>",
          "description": "The red Alliance may choose to place last",
          "link": "https://www.vexrobotics.com/override-manual#gg10"
        },
        {
          "rule": "<GG11>",
          "description": "Controllers must stay connected to the Field",
          "link": "https://www.vexrobotics.com/override-manual#gg11"
        },
        {
          "rule": "<GG12>",
          "description": "Autonomous means \"no humans\"",
          "link": "https://www.vexrobotics.com/override-manual#gg12"
        },
        {
          "rule": "<GG13>",
          "description": "All rules still apply in the Autonomous Period",
          "link": "https://www.vexrobotics.com/override-manual#gg13"
        },
        {
          "rule": "<GG14>",
          "description": "Don't destroy other Robots. But, be prepared to encounter defense",
          "link": "https://www.vexrobotics.com/override-manual#gg14"
        },
        {
          "rule": "<GG15>",
          "description": "Offensive Robots get the \"benefit of the doubt\" when judgment calls are required",
          "link": "https://www.vexrobotics.com/override-manual#gg15"
        },
        {
          "rule": "<GG16>",
          "description": "You can't force an opponent into a penalty",
          "link": "https://www.vexrobotics.com/override-manual#gg16"
        },
        {
          "rule": "<GG17>",
          "description": "No Holding for more than a 3-count",
          "link": "https://www.vexrobotics.com/override-manual#gg17"
        },
        {
          "rule": "<GG18>",
          "description": "Use Scoring Objects to play the game",
          "link": "https://www.vexrobotics.com/override-manual#gg18"
        }
      ]
    },
    {
      "name": "General Rules",
      "programs": [
        "V5RC",
        "VURC",
        "VAIRC"
      ],
      "rules": [
        {
          "rule": "<G1>",
          "description": "Treat everyone with respect",
          "link": "https://www.vexrobotics.com/override-manual#g1"
        },
        {
          "rule": "<G2>",
          "description": "V5RC is a Student-centered program",
          "link": "https://www.vexrobotics.com/override-manual#g2"
        },
        {
          "rule": "<G3>",
          "description": "Use common sense",
          "link": "https://www.vexrobotics.com/override-manual#g3"
        },
        {
          "rule": "<G4>",
          "description": "All work must represent the skill level of the Students on the Team",
          "link": "https://www.vexrobotics.com/override-manual#g4"
        },
        {
          "rule": "<G5>",
          "description": "Each Student can only belong to one Team",
          "link": "https://www.vexrobotics.com/override-manual#g5"
        },
        {
          "rule": "<G6>",
          "description": "There is a difference between accidentally and willfully violating a Robot rule",
          "link": "https://www.vexrobotics.com/override-manual#g6"
        }
      ]
    },
    {
      "name": "Safety Rules",
      "programs": [
        "V5RC",
        "VURC",
        "VAIRC"
      ],
      "rules": [
        {
          "rule": "<S1>",
          "description": "Be safe out there",
          "link": "https://www.vexrobotics.com/override-manual#s1"
        },
        {
          "rule": "<S2>",
          "description": "Students must be accompanied by an Adult",
          "link": "https://www.vexrobotics.com/override-manual#s2"
        },
        {
          "rule": "<S3>",
          "description": "Each Student Team member must have a completed participant release form on file",
          "link": "https://www.vexrobotics.com/override-manual#s3"
        },
        {
          "rule": "<S4>",
          "description": "Stay inside the Field",
          "link": "https://www.vexrobotics.com/override-manual#s4"
        },
        {
          "rule": "<S5>",
